@startuml SequenceDiagram
title Join Private Class
actor User

participant ": Frontend" as Frontend
participant ": Router" as Router
participant ": Middleware" as Middleware

participant ": ClassController" as ClassController
participant ": ClassService" as ClassService
participant ": ClassRepository" as ClassRepository

participant ": EnrollmentController" as EnrollmentController
participant ": EnrollmentService" as EnrollmentService
participant ": EnrollmentRepository" as EnrollmentRepository

database Database

User -> Frontend: .handleJoinPrivateClassClick()
Frontend -> User: Show join private class form

User -> Frontend: .handleJoinPrivateClassSubmit(invitationCode)
Frontend -> Router: POST /api/enrollments/{invitationCode}
activate Router

Router -> Middleware: .Use(Middleware)
activate Middleware
Middleware -> Middleware : .Verify()

alt Unauthorized (401 Unauthorized)
  Middleware -->> Router: 401 Unauthorized
  Router -->> Frontend: 401 Unauthorized
  Frontend -->> User: Show error "Please log in"
else Authorized
  Middleware -->> Router: Route to Router
  deactivate Middleware
  Router -> EnrollmentController: .JoinPrivateClass(invitationCode)
  activate EnrollmentController
  EnrollmentController -> EnrollmentService: .JoinPrivateClass(invitationCode)
  activate EnrollmentService
  EnrollmentService -> EnrollmentRepository: .JoinPrivateClass(invitationCode)
  activate EnrollmentRepository
  EnrollmentRepository -> Database: INSERT INTO user_classes (user_id, class_id) VALUES (@user_id, @class_id)
  activate Database
  Database -->> EnrollmentRepository : user_classes, Error
  deactivate Database
  EnrollmentRepository -> Database: INSERT INTO user_courses (user_id, class_id) VALUES (@user_id, @class_id)
  activate Database
  Database -->> EnrollmentRepository : user_courses, Error
  deactivate Database
  EnrollmentRepository -->> EnrollmentService : Enrollment, Error
  deactivate EnrollmentRepository
  EnrollmentService -->> EnrollmentController : Enrollment, Error
  deactivate EnrollmentService
  alt Error != Null
    EnrollmentController -->> Router : 500 Internal Server Error
    Router -->> Frontend : 500 Internal Server Error
    Frontend -->> User : Show error "Failed to join class"
  else Enrollment == Null
    EnrollmentController -->> Router : 404 Not Found
    Router -->> Frontend : 404 Not Found
    Frontend -->> User : Show message "Class not found"
  else
    EnrollmentController -->> Router : 200 OK
    Router -->> Frontend : 200 OK
    Frontend -->> User : Show susccess "Joined class"
  end
  deactivate EnrollmentController
  deactivate Router
end



@enduml